//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InPageToAutographa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxCorrectYearSignChecked {
            get {
                return ((bool)(this["CheckboxCorrectYearSignChecked"]));
            }
            set {
                this["CheckboxCorrectYearSignChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxCorrectHehHamzaChecked {
            get {
                return ((bool)(this["CheckboxCorrectHehHamzaChecked"]));
            }
            set {
                this["CheckboxCorrectHehHamzaChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxCorrectWawHamzaChecked {
            get {
                return ((bool)(this["CheckboxCorrectWawHamzaChecked"]));
            }
            set {
                this["CheckboxCorrectWawHamzaChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxCorrectBariYeeChecked {
            get {
                return ((bool)(this["CheckboxCorrectBariYeeChecked"]));
            }
            set {
                this["CheckboxCorrectBariYeeChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxRemoveDoubleSpaceChecked {
            get {
                return ((bool)(this["CheckboxRemoveDoubleSpaceChecked"]));
            }
            set {
                this["CheckboxRemoveDoubleSpaceChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckboxRemoveKashidaChecked {
            get {
                return ((bool)(this["CheckboxRemoveKashidaChecked"]));
            }
            set {
                this["CheckboxRemoveKashidaChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckboxRemoveErabsChecked {
            get {
                return ((bool)(this["CheckboxRemoveErabsChecked"]));
            }
            set {
                this["CheckboxRemoveErabsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxReverseNumbersDigitsChecked {
            get {
                return ((bool)(this["CheckboxReverseNumbersDigitsChecked"]));
            }
            set {
                this["CheckboxReverseNumbersDigitsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxReverseSolidusSignChecked {
            get {
                return ((bool)(this["CheckboxReverseSolidusSignChecked"]));
            }
            set {
                this["CheckboxReverseSolidusSignChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxReverseThousSeparatorChecked {
            get {
                return ((bool)(this["CheckboxReverseThousSeparatorChecked"]));
            }
            set {
                this["CheckboxReverseThousSeparatorChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckboxReverseQuotMarksChecked {
            get {
                return ((bool)(this["CheckboxReverseQuotMarksChecked"]));
            }
            set {
                this["CheckboxReverseQuotMarksChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckboxChangePChecked {
            get {
                return ((bool)(this["CheckboxChangePChecked"]));
            }
            set {
                this["CheckboxChangePChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxChangeCCChecked {
            get {
                return ((bool)(this["CheckboxChangeCCChecked"]));
            }
            set {
                this["CheckboxChangeCCChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxAdditionalBaariYieChecked {
            get {
                return ((bool)(this["CheckboxAdditionalBaariYieChecked"]));
            }
            set {
                this["CheckboxAdditionalBaariYieChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckboxAdditionalKashidaChecked {
            get {
                return ((bool)(this["CheckboxAdditionalKashidaChecked"]));
            }
            set {
                this["CheckboxAdditionalKashidaChecked"] = value;
            }
        }
    }
}
